[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
goerli = "${ALCHEMY_RPC}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
